# Generated by Django 5.2.2 on 2025-06-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hall',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hall',
            name='amenities',
            field=models.ManyToManyField(related_name='halls', to='event_system.amenity'),
        ),
    ]
