# Generated by Django 5.2.2 on 2025-06-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system', '0002_amenity_remove_hall_amenities_hall_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
