# Generated by Django 5.2.2 on 2025-06-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_system', '0004_alter_booking_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='price_per_hour',
            new_name='price_per_day',
        ),
    ]
