# Generated by Django 5.2.2 on 2025-06-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('debit_card', 'Debit Card'), ('upi', 'UPI')], default='upi_id', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
