# Generated by Django 5.1.7 on 2025-06-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system', '0007_payment_payment_method_payment_upi_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
