# Generated by Django 5.1.7 on 2025-06-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_system', '0008_remove_booking_end_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='start_datetime',
        ),
    ]
