# Generated by Django 5.1.7 on 2025-06-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system', '0010_alter_booking_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
